input {
  beats {
    port => 5044
  }
}

filter {
  if [service] == "nginx" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
      overwrite => ["message"]
      add_field => { "[@metadata][index]" => "nginx" }
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
    mutate {
      convert => { "status" => "integer" "bytes" => "integer" }
    }
    geoip {
      source => "clientip"
      target => "geoip"
      add_field => { "country" => "%{[geoip][country_name]}" }
    }
  }

  if [service] == "ssh" {
    json {
      source => "message"
      target => "ssh_data"
    }
    date {
      match => [ "[ssh_data][timestamp]", "ISO8601" ]
      target => "@timestamp"
    }
    mutate {
      rename => { "[ssh_data][user]" => "ssh_user" }
      rename => { "[ssh_data][source_ip]" => "ssh_ip" }
      rename => { "[ssh_data][result]" => "ssh_result" }
      rename => { "[ssh_data][country]" => "ssh_country" }
      add_field => { "[@metadata][index]" => "ssh" }
      remove_field => ["ssh_data"]
    }
    geoip {
      source => "ssh_ip"
      target => "geoip"
      add_field => { "ssh_country" => "%{[geoip][country_name]}" }
    }
  }

  if [service] == "syslog" {
    grok {
      match => { "message" => "<%{POSINT:priority}>%{NONZERO_INT:version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:hostname} %{NOTSPACE:process} %{INT:pid} %{NOTSPACE} %{GREEDYDATA:message}" }
      overwrite => ["message"]
      add_field => { "[@metadata][index]" => "syslog" }
    }
    mutate {
      convert => { "priority" => "integer" }
    }
  }

  if [service] == "app" {
    json {
      source => "message"
      target => "app_data"
    }
    date {
      match => [ "[app_data][timestamp]", "ISO8601" ]
      target => "@timestamp"
    }
    mutate {
      rename => { "[app_data][method]" => "request_method" }
      rename => { "[app_data][endpoint]" => "request_endpoint" }
      rename => { "[app_data][status_code]" => "request_status" }
      rename => { "[app_data][latency_ms]" => "request_latency" }
      add_field => { "[@metadata][index]" => "app" }
      remove_field => ["app_data"]
    }
  }

  mutate {
    add_field => { "lab" => "elk-observability" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
    manage_template => false
  }
  stdout {
    codec => rubydebug
  }
}