input {
  beats {
    port => 5044
  }
}

filter {
  if [service] == "nginx" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
      overwrite => ["message"]
    }

    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }

    geoip {
      source => "clientip"
      target => "geoip"
    }

    mutate {
      add_field => { "[@metadata][index]" => "nginx" }
    }
  }

  if [service] == "windows" {
    if [event_type] == "security" {
      if [event_id] == 4624 {
        mutate {
          add_field => { "logon_result" => "success" }
        }
      }
      if [event_id] == 4625 {
        mutate {
          add_field => { "logon_result" => "failure" }
        }
      }
    }

    date {
      match => ["@timestamp"]
      target => "@timestamp"
    }

    mutate {
      add_field => { "[@metadata][index]" => "windows" }
    }
  }

  mutate {
    add_field => { "lab" => "elk-observability" }
  }
}

output {
  if [service] == "nginx" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "logs-nginx-%{+YYYY.MM.dd}"
      manage_template => false
    }
  }

  if [service] == "windows" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "logs-windows-%{+YYYY.MM.dd}"
      manage_template => false
    }
  }

  stdout {
    codec => rubydebug
  }
}